### PR TITLE
Add echopet.pet.baby.*

### PR DESCRIPTION
**Pull request by andrewkm**
This will heavily help my permissions re-write as I'm finally updating to 1.14.4
Further more you are already doing it with hat.* and ride.* :)
Made sure to check that only correct baby pets included.

### CODE REVIEW

**Comment by Arnuh** [comment]
plugin.yml is generated from https://github.com/Arnuh/EchoPet/blob/v1_14_R1/modules/API/src/com/dsh105/echopet/compat/api/entity/PetType.java#L319

Without this added into that method I'll just delete it next pet data I add.

**Comment by andrewkm** [comment]
@arnuh oh rip :(
Hoping you can add this during your next update then <3. That’s about as far as my none existent development knowledge goes lmao.

**Comment by Arnuh** [comment]
Resolved in https://github.com/Arnuh/EchoPet/commit/a06b44ac6b274ce7b9bcb34634ce3d989e66139a

**Comment by andrewkm** [comment]
You’re the man :)

**Pull request closed without merging**
